config/routes.rb
# Route prefixes use a single letter to allow for vanity urls of two or more characters
Rails.application.routes.draw do
  resources :gibbs_rates_observations
  if defined? Sidekiq
    require 'sidekiq/web'
    authenticate :user, lambda {|u| u.is_admin? } do
      mount Sidekiq::Web, at: '/admin/sidekiq/jobs', as: :sidekiq
    end
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin' if defined? RailsAdmin

  # Static pages
  match '/error' => 'pages#error', via: [:get, :post], as: 'error_page'
  get '/terms' => 'pages#terms', as: 'terms'
  get '/privacy' => 'pages#privacy', as: 'privacy'
  get '/about' => 'pages#about', as: 'about'
  get '/as' => 'pages#as', as: 'as'
  get '/redoxmodel' => 'pages#redoxmodel', as: 'redoxmodel'

  # OAuth
  oauth_prefix = Rails.application.config.auth.omniauth.path_prefix
  get "#{oauth_prefix}/:provider/callback" => 'users/oauth#create'
  get "#{oauth_prefix}/failure" => 'users/oauth#failure'
  get "#{oauth_prefix}/:provider" => 'users/oauth#passthru', as: 'provider_auth'
  get oauth_prefix => redirect("#{oauth_prefix}/login")

  # Devise
  devise_prefix = Rails.application.config.auth.devise.path_prefix
  devise_for :users, path: devise_prefix,
    controllers: {registrations: 'users/registrations', sessions: 'users/sessions',
      passwords: 'users/passwords', confirmations: 'users/confirmations', unlocks: 'users/unlocks'},
    path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}
  devise_scope :user do
    get "#{devise_prefix}/after" => 'users/registrations#after_auth', as: 'user_root'
  end
  get devise_prefix => redirect('/a/signup')

  # User
  resources :users, path: 'u', only: :show do
    resources :authentications, path: 'accounts'
  end
  get '/home' => 'users#show', as: 'user_home'

  # Dummy preview pages for testing.
  get '/p/test' => 'pages#test', as: 'test'
  get '/p/email' => 'pages#email' if ENV['ALLOW_EMAIL_PREVIEW'].present?

  get 'robots.:format' => 'robots#index'

  root 'pages#home'
end

app/models/observation.rb
class Observation < ActiveRecord::Base
  belongs_to  :user

  def owner
    User.find_by_id(self.user_id)
  end
end

app/helpers/observations_helper.rb
module ObservationsHelper

  def gibbs_units
    ['kJ/M','J/M','kJ/M EA', 'kJ/M ED', 'kJ/M/e','J/M EA', 'J/M ED', 'J/M/e']
  end

  def rate_units
     ['M/s','M/h','M/year','mM/s','mM/h','mM/year','uM/s','uM/h','uM/year']   
  end

  def first_author(ref)
    ref.split(/,\s*/)[0..1].join(', ') + ', ' + ref.match(/[0-9]{4}/).try(:to_s)
  end
end

app/views/observations/_form.html.haml
= simple_form_for(@observation) do |f|
  = f.error_notification
  .form-inputs
    .row
      .col-sm-6
        = f.input :reaction_name, placeholder: "ex: sulfate reduction, glucose oxidation, etc."
        = f.input :donor, label: "Terminal Electron Donor", placeholder: "ex: glucose, hydrogen"
        = f.input :acceptor, label: "Terminal Electron Acceptor", placeholder: "ex: sulfate, hydrogen"
        = f.input :reaction, label: "Chemical Reaction", placeholder: "ex: 3C6H12O6 + 3SO4^{2-} + 21H{+}  -> 6CH3COO{-} + 12H2 + 6CO2 + 3HS{-} + 6H2O"
        .row
          .col-sm-6
            Measured in the lab or in Situ?:
          .col-sm-6
            = f.label :lab, "Lab" 
            = f.radio_button :lab, true, :value => true
            = f.label :lab, "in Situ" 
            = f.radio_button :lab, false, :value => false
        .row
          .col-sm-8
            = f.input :rate, label: "Rate of the Chemical Reaction", placeholder: "ex: 3.13E-13, 0.0000001"
          .col-sm-4
            = f.label :rate_units, "Units:" 
            = f.select :rate_units, options_for_select(rate_units), {}, {class: "form-control"}
        .row
          .col-sm-8
            = f.input :gibbs_energy, label: "Gibbs Energy of Reaction (non-standard)", placeholder: "ex: 4.48E+5, 448000"
          .col-sm-4
            = f.label :gibbs_units, "Units:" 
            = f.select :gibbs_units, options_for_select(gibbs_units), {}, {class: "form-control"}

        = f.input :reference, label: "Reference to the paper", placeholder: "ex: Røy, H., Kallmeyer, J., Adhikari, R. R., Pockalny, R., Jørgensen, B. B., & D'Hondt, S. (2012). Aerobic microbial respiration in 86-million-year-old deep-sea red clay. Science, 336(6083), 922–925. http://doi.org/10.1126/science.1219424"
        = f.input :paper, label: "Reference to the paper where it was found" ,placeholder: "ex: LaRowe, D. E., & Amend, J. P. (2015). Catabolic rates, population sizes and doubling/replacement times of microorganisms in natural settings. American Journal of Science, 315(3), 167–203. http://doi.org/10.2475/03.2015.01", hint: "fill this if you found the data not in the original paper but in different with reference to the original"
        =f.input :add_info, label: "Additional information about measurements", placeholder: "ex: Concentrations of elements or bacteria, Depth of the measurements, temperature..."
      .col-sm-6
        = f.input :location_name, placeholder: "ex: Gulf of Mexico"
        %b Select the new place to update the coordinates:      
        #map{style: 'width: 400px; height: 400px;'}
        -# %b Or type the coordinates(+N and +E , -S and -W):
        = f.hidden_field :lat, id: 'map_lat', label: "Latitude"
        = f.hidden_field :lng, id: 'map_lng', label: "Longitude"
        %p
        = f.input :environment_type, placeholder: "ex: open ocean sediments, mud volcano / seafloor brine", hint: "marine brine pool , continental margin sediments, marine cold seep sediments, lake sediments, submarine mud volcanoes, shelf and trough sediments, diffuse hydrothermal vent, open ocean sediments, etc.. "

    .row
      = link_to 'Back', observations_path
      = f.button :submit, class: "btn btn-primary pull-right"

:javascript
  $(document).ready(function(){
    var observation = #{@observation.to_json}
    gmap_form(observation);    // form map for edit view (print marker and possibility of put newer)
  });

app/views/observations/_form_edit.html.haml
= simple_form_for(@observation) do |f|
  = f.error_notification
  .form-inputs
    .row
      .col-sm-6
        = f.input :reaction_name, placeholder: "ex: sulfate reduction, glucose oxidation, etc."
        = f.input :donor, label: "Terminal Electron Donor", placeholder: "ex: glucose, hydrogen"
        = f.input :acceptor, label: "Terminal Electron Acceptor", placeholder: "ex: sulfate, hydrogen"
        = f.input :reaction, label: "Chemical Reaction", placeholder: "ex: 3C6H12O6 + 3SO4^{2-} + 21H{+}  -> 6CH3COO{-} + 12H2 + 6CO2 + 3HS{-} + 6H2O"
        .row
          .col-sm-6
            Measured in the lab or in Situ?:
          .col-sm-6
            = f.label :lab, "Lab" 
            = f.radio_button :lab, true, :value => true
            = f.label :lab, "in Situ" 
            = f.radio_button :lab, false, :value => false
        .row
          .col-sm-8
            = f.input :rate, label: "Rate of the Chemical Reaction", placeholder: "ex: 3.13E-13, 0.0000001"
          .col-sm-4
            = f.label :rate_units, "Units:" 
            = f.select :rate_units, options_for_select(rate_units), {}, {class: "form-control"}
        .row
          .col-sm-8
            = f.input :gibbs_energy, label: "Gibbs Energy of Reaction (non-standard)", placeholder: "ex: 4.48E+5, 448000"
          .col-sm-4
            = f.label :gibbs_units, "Units:" 
            = f.select :gibbs_units, options_for_select(gibbs_units), {}, {class: "form-control"}

        = f.input :reference, label: "Reference to the paper", placeholder: "ex: Røy, H., Kallmeyer, J., Adhikari, R. R., Pockalny, R., Jørgensen, B. B., & D'Hondt, S. (2012). Aerobic microbial respiration in 86-million-year-old deep-sea red clay. Science, 336(6083), 922–925. http://doi.org/10.1126/science.1219424"
        = f.input :paper, label: "Reference to the paper where it was found" ,placeholder: "ex: LaRowe, D. E., & Amend, J. P. (2015). Catabolic rates, population sizes and doubling/replacement times of microorganisms in natural settings. American Journal of Science, 315(3), 167–203. http://doi.org/10.2475/03.2015.01", hint: "fill this if you found the data not in the original paper but in different with reference to the original"
        =f.input :add_info, label: "Additional information about measurements", placeholder: "ex: Concentrations of elements or bacteria, Depth of the measurements, temperature..."
      .col-sm-6
        = f.input :location_name, placeholder: "ex: Gulf of Mexico"
        %b Select the new place to update the coordinates:      
        #map{style: 'width: 400px; height: 400px;'}
        %b Or type the coordinates(+N and +E , -S and -W):
        = f.input :lat, id: 'map_lat', label: "Latitude"
        = f.input :lng, id: 'map_lng', label: "Longitude"
        = f.input :environment_type, placeholder: "ex: open ocean sediments, mud volcano / seafloor brine", hint: "marine brine pool , continental margin sediments, marine cold seep sediments, lake sediments, submarine mud volcanoes, shelf and trough sediments, diffuse hydrothermal vent, open ocean sediments, etc.. "

    .row
      = link_to 'Back', observations_path
      = f.button :submit, class: "btn btn-primary pull-right"

:javascript
  $(document).ready(function(){
    var observation = #{@observation.to_json}
    gmap_form(observation);    // form map for edit view (print marker and possibility of put newer)
  });

app/views/observations/_form_new.html.haml
= simple_form_for(@observation) do |f|
  = f.error_notification
  .form-inputs
    .row
      .col-md-4
        = f.input :reaction_name, placeholder: "hint: sulfate reduction, glucose oxidation, etc."
        = f.input :donor, label: "Terminal Electron Donor", placeholder: "glucose, hydrogen"
        = f.input :acceptor, label: "Terminal Electron Acceptor", placeholder: "sulfate, hydrogen"
        = f.input :reaction, label: "Chemical Reaction", placeholder: "3C6H12O6 + 3SO4^{2-} + 21H{+}  -> 6CH3COO{-} + 12H2 + 6CO2 + 3HS{-} + 6H2O"
      .col-md-4
        = f.input :lab, label: "Measured in the lab or in Situ? Check if Lab"
        = f.input :environment_type, placeholder: "open ocean sediments, mud volcano / seafloor brine", hint: "marine brine pool , continental margin sediments, marine cold seep sediments, hydrothermal sediments, submarine mud volcanoes, shelf and trough sediments, diffuse hydrothermal vent,open ocean sediments, etc.. "
        = f.input :location_name, placeholder: "Gulf of Mexico"
      .col-md-4
        = f.input :rate, label: "Rate of the Chemical Reaction", placeholder: "3.13E-13, 0.0000001"
        = f.input :gibbs_energy, label: "Gibbs Energy of Reaction", placeholder: "4.48E+5, 448000"
        = f.input :reference, label: "Reference to the paper", placeholder: "Røy, H., Kallmeyer, J., Adhikari, R. R., Pockalny, R., Jørgensen, B. B., & D'Hondt, S. (2012). Aerobic microbial respiration in 86-million-year-old deep-sea red clay. Science, 336(6083), 922–925. http://doi.org/10.1126/science.1219424"
        = f.input :paper, label: "Reference to the paper where it was found" ,placeholder: "LaRowe, D. E., & Amend, J. P. (2015). Catabolic rates, population sizes and doubling/replacement times of microorganisms in natural settings. American Journal of Science, 315(3), 167–203. http://doi.org/10.2475/03.2015.01", hint: "fill this if you found the data not in the original paper but in different with reference to the original"
    .row
      .col-md-4
        .form-actions
          = f.button :submit, class: "btn btn-primary"
          