config/routes.rb
# Route prefixes use a single letter to allow for vanity urls of two or more characters
Rails.application.routes.draw do
  resources :gibbs_rates_observations
  if defined? Sidekiq
    require 'sidekiq/web'
    authenticate :user, lambda {|u| u.is_admin? } do
      mount Sidekiq::Web, at: '/admin/sidekiq/jobs', as: :sidekiq
    end
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin' if defined? RailsAdmin

  # Static pages
  match '/error' => 'pages#error', via: [:get, :post], as: 'error_page'
  get '/terms' => 'pages#terms', as: 'terms'
  get '/privacy' => 'pages#privacy', as: 'privacy'
  get '/about' => 'pages#about', as: 'about'
  get '/as' => 'pages#as', as: 'as'
  get '/redoxmodel' => 'pages#redoxmodel', as: 'redoxmodel'

  # OAuth
  oauth_prefix = Rails.application.config.auth.omniauth.path_prefix
  get "#{oauth_prefix}/:provider/callback" => 'users/oauth#create'
  get "#{oauth_prefix}/failure" => 'users/oauth#failure'
  get "#{oauth_prefix}/:provider" => 'users/oauth#passthru', as: 'provider_auth'
  get oauth_prefix => redirect("#{oauth_prefix}/login")

  # Devise
  devise_prefix = Rails.application.config.auth.devise.path_prefix
  devise_for :users, path: devise_prefix,
    controllers: {registrations: 'users/registrations', sessions: 'users/sessions',
      passwords: 'users/passwords', confirmations: 'users/confirmations', unlocks: 'users/unlocks'},
    path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}
  devise_scope :user do
    get "#{devise_prefix}/after" => 'users/registrations#after_auth', as: 'user_root'
  end
  get devise_prefix => redirect('/a/signup')

  # User
  resources :users, path: 'u', only: :show do
    resources :authentications, path: 'accounts'
  end
  get '/home' => 'users#show', as: 'user_home'

  # Dummy preview pages for testing.
  get '/p/test' => 'pages#test', as: 'test'
  get '/p/email' => 'pages#email' if ENV['ALLOW_EMAIL_PREVIEW'].present?

  get 'robots.:format' => 'robots#index'

  root 'pages#home'
end

app/models/gibbs_rates_observation.rb
class GibbsRatesObservation < ActiveRecord::Base
  belongs_to  :user

  def owner
    User.find_by_id(self.user_id)
  end
end

app/controllers/gibbs_rates_observations_controller.rb
class GibbsRatesObservationsController < ApplicationController
  # skip_authorization_check
  load_and_authorize_resource
  before_action :set_gibbs_rates_observation, only: [:show, :edit, :update, :destroy]

  # GET /gibbs_rates_observations


  def index
    @gibbs_rates_observations = GibbsRatesObservation.all
    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"gibbs_rates_observations-db.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  # GET /gibbs_rates_observations/1
  def show
  end

  # GET /gibbs_rates_observations/new
  def new
    @gibbs_rates_observation = GibbsRatesObservation.new
  end

  # GET /gibbs_rates_observations/1/edit
  def edit
  end

  # POST /gibbs_rates_observations
  def create
    @gibbs_rates_observation = GibbsRatesObservation.new(gibbs_rates_observation_params)
    @gibbs_rates_observation.user_id = current_user.id

    if @gibbs_rates_observation.save
      redirect_to @gibbs_rates_observation, notice: 'GibbsRatesObservation was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gibbs_rates_observations/1
  def update
    if @gibbs_rates_observation.update(gibbs_rates_observation_params)
      redirect_to @gibbs_rates_observation, notice: 'GibbsRatesObservation was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gibbs_rates_observations/1
  def destroy
    @gibbs_rates_observation.destroy
    redirect_to gibbs_rates_observations_url, notice: 'GibbsRatesObservation was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gibbs_rates_observation
      @gibbs_rates_observation = GibbsRatesObservation.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def gibbs_rates_observation_params
      params.require(:gibbs_rates_observation).permit(:reaction_name, :donor, :acceptor, :reaction, :lab, :environment_type, :location_name, :rate, :gibbs_energy, :reference, :paper, :user_id, :lat, :lng, :add_info, :gibbs_units, :rate_units)
    end
end

app/helpers/gibbs_rates_observations_helper.rb
module GibbsRatesObservationsHelper

  def gibbs_units
    ['kJ/M','J/M','kJ/M EA', 'kJ/M ED', 'kJ/M/e','J/M EA', 'J/M ED', 'J/M/e']
  end

  def rate_units
     ['M/s','M/h','M/year','mM/s','mM/h','mM/year','uM/s','uM/h','uM/year']   
  end

  def first_author(ref)
    ref.split(/,\s*/)[0..1].join(', ') + ', ' + ref.match(/[0-9]{4}/).try(:to_s)
  end
end

app/views/gibbs_rates_observations/_form.html.haml
= simple_form_for(@gibbs_rates_observation) do |f|
  = f.error_notification
  .form-inputs
    .row
      .col-sm-6
        = f.input :reaction_name, placeholder: "ex: sulfate reduction, glucose oxidation, etc."
        = f.input :donor, label: "Terminal Electron Donor", placeholder: "ex: glucose, hydrogen"
        = f.input :acceptor, label: "Terminal Electron Acceptor", placeholder: "ex: sulfate, hydrogen"
        = f.input :reaction, label: "Chemical Reaction", placeholder: "ex: 3C6H12O6 + 3SO4^{2-} + 21H{+}  -> 6CH3COO{-} + 12H2 + 6CO2 + 3HS{-} + 6H2O"
        .row
          .col-sm-6
            Measured in the lab or in Situ?:
          .col-sm-6
            = f.label :lab, "Lab" 
            = f.radio_button :lab, true, :value => true
            = f.label :lab, "in Situ" 
            = f.radio_button :lab, false, :value => false
        .row
          .col-sm-8
            = f.input :rate, label: "Rate of the Chemical Reaction", placeholder: "ex: 3.13E-13, 0.0000001"
          .col-sm-4
            = f.label :rate_units, "Units:" 
            = f.select :rate_units, options_for_select(rate_units), {}, {class: "form-control"}
        .row
          .col-sm-8
            = f.input :gibbs_energy, label: "Gibbs Energy of Reaction (non-standard)", placeholder: "ex: 4.48E+5, 448000"
          .col-sm-4
            = f.label :gibbs_units, "Units:" 
            = f.select :gibbs_units, options_for_select(gibbs_units), {}, {class: "form-control"}

        = f.input :reference, label: "Reference to the paper", placeholder: "ex: Røy, H., Kallmeyer, J., Adhikari, R. R., Pockalny, R., Jørgensen, B. B., & D'Hondt, S. (2012). Aerobic microbial respiration in 86-million-year-old deep-sea red clay. Science, 336(6083), 922–925. http://doi.org/10.1126/science.1219424"
        = f.input :paper, label: "Reference to the paper where it was found" ,placeholder: "ex: LaRowe, D. E., & Amend, J. P. (2015). Catabolic rates, population sizes and doubling/replacement times of microorganisms in natural settings. American Journal of Science, 315(3), 167–203. http://doi.org/10.2475/03.2015.01", hint: "fill this if you found the data not in the original paper but in different with reference to the original"
        =f.input :add_info, label: "Additional information about measurements", placeholder: "ex: Concentrations of elements or bacteria, Depth of the measurements, temperature..."
      .col-sm-6
        = f.input :location_name, placeholder: "ex: Gulf of Mexico"
        %b Select the new place to update the coordinates:      
        #map{style: 'width: 400px; height: 400px;'}
        -# %b Or type the coordinates(+N and +E , -S and -W):
        = f.hidden_field :lat, id: 'map_lat', label: "Latitude"
        = f.hidden_field :lng, id: 'map_lng', label: "Longitude"
        %p
        = f.input :environment_type, placeholder: "ex: open ocean sediments, mud volcano / seafloor brine", hint: "marine brine pool , continental margin sediments, marine cold seep sediments, lake sediments, submarine mud volcanoes, shelf and trough sediments, diffuse hydrothermal vent, open ocean sediments, etc.. "

    .row
      = link_to 'Back', gibbs_rates_observations_path
      = f.button :submit, class: "btn btn-primary pull-right"

:javascript
  $(document).ready(function(){
    var gibbs_rates_observation = #{@gibbs_rates_observation.to_json}
    gmap_form(gibbs_rates_observation);    // form map for edit view (print marker and possibility of put newer)
  });

app/views/gibbs_rates_observations/_form_edit.html.haml
= simple_form_for(@gibbs_rates_observation) do |f|
  = f.error_notification
  .form-inputs
    .row
      .col-sm-6
        = f.input :reaction_name, placeholder: "ex: sulfate reduction, glucose oxidation, etc."
        = f.input :donor, label: "Terminal Electron Donor", placeholder: "ex: glucose, hydrogen"
        = f.input :acceptor, label: "Terminal Electron Acceptor", placeholder: "ex: sulfate, hydrogen"
        = f.input :reaction, label: "Chemical Reaction", placeholder: "ex: 3C6H12O6 + 3SO4^{2-} + 21H{+}  -> 6CH3COO{-} + 12H2 + 6CO2 + 3HS{-} + 6H2O"
        .row
          .col-sm-6
            Measured in the lab or in Situ?:
          .col-sm-6
            = f.label :lab, "Lab" 
            = f.radio_button :lab, true, :value => true
            = f.label :lab, "in Situ" 
            = f.radio_button :lab, false, :value => false
        .row
          .col-sm-8
            = f.input :rate, label: "Rate of the Chemical Reaction", placeholder: "ex: 3.13E-13, 0.0000001"
          .col-sm-4
            = f.label :rate_units, "Units:" 
            = f.select :rate_units, options_for_select(rate_units), {}, {class: "form-control"}
        .row
          .col-sm-8
            = f.input :gibbs_energy, label: "Gibbs Energy of Reaction (non-standard)", placeholder: "ex: 4.48E+5, 448000"
          .col-sm-4
            = f.label :gibbs_units, "Units:" 
            = f.select :gibbs_units, options_for_select(gibbs_units), {}, {class: "form-control"}

        = f.input :reference, label: "Reference to the paper", placeholder: "ex: Røy, H., Kallmeyer, J., Adhikari, R. R., Pockalny, R., Jørgensen, B. B., & D'Hondt, S. (2012). Aerobic microbial respiration in 86-million-year-old deep-sea red clay. Science, 336(6083), 922–925. http://doi.org/10.1126/science.1219424"
        = f.input :paper, label: "Reference to the paper where it was found" ,placeholder: "ex: LaRowe, D. E., & Amend, J. P. (2015). Catabolic rates, population sizes and doubling/replacement times of microorganisms in natural settings. American Journal of Science, 315(3), 167–203. http://doi.org/10.2475/03.2015.01", hint: "fill this if you found the data not in the original paper but in different with reference to the original"
        =f.input :add_info, label: "Additional information about measurements", placeholder: "ex: Concentrations of elements or bacteria, Depth of the measurements, temperature..."
      .col-sm-6
        = f.input :location_name, placeholder: "ex: Gulf of Mexico"
        %b Select the new place to update the coordinates:      
        #map{style: 'width: 400px; height: 400px;'}
        %b Or type the coordinates(+N and +E , -S and -W):
        = f.input :lat, id: 'map_lat', label: "Latitude"
        = f.input :lng, id: 'map_lng', label: "Longitude"
        = f.input :environment_type, placeholder: "ex: open ocean sediments, mud volcano / seafloor brine", hint: "marine brine pool , continental margin sediments, marine cold seep sediments, lake sediments, submarine mud volcanoes, shelf and trough sediments, diffuse hydrothermal vent, open ocean sediments, etc.. "

    .row
      = link_to 'Back', gibbs_rates_observations_path
      = f.button :submit, class: "btn btn-primary pull-right"

:javascript
  $(document).ready(function(){
    var gibbs_rates_observation = #{@gibbs_rates_observation.to_json}
    gmap_form(gibbs_rates_observation);    // form map for edit view (print marker and possibility of put newer)
  });

app/views/gibbs_rates_observations/_form_new.html.haml
= simple_form_for(@gibbs_rates_observation) do |f|
  = f.error_notification
  .form-inputs
    .row
      .col-md-4
        = f.input :reaction_name, placeholder: "hint: sulfate reduction, glucose oxidation, etc."
        = f.input :donor, label: "Terminal Electron Donor", placeholder: "glucose, hydrogen"
        = f.input :acceptor, label: "Terminal Electron Acceptor", placeholder: "sulfate, hydrogen"
        = f.input :reaction, label: "Chemical Reaction", placeholder: "3C6H12O6 + 3SO4^{2-} + 21H{+}  -> 6CH3COO{-} + 12H2 + 6CO2 + 3HS{-} + 6H2O"
      .col-md-4
        = f.input :lab, label: "Measured in the lab or in Situ? Check if Lab"
        = f.input :environment_type, placeholder: "open ocean sediments, mud volcano / seafloor brine", hint: "marine brine pool , continental margin sediments, marine cold seep sediments, hydrothermal sediments, submarine mud volcanoes, shelf and trough sediments, diffuse hydrothermal vent,open ocean sediments, etc.. "
        = f.input :location_name, placeholder: "Gulf of Mexico"
      .col-md-4
        = f.input :rate, label: "Rate of the Chemical Reaction", placeholder: "3.13E-13, 0.0000001"
        = f.input :gibbs_energy, label: "Gibbs Energy of Reaction", placeholder: "4.48E+5, 448000"
        = f.input :reference, label: "Reference to the paper", placeholder: "Røy, H., Kallmeyer, J., Adhikari, R. R., Pockalny, R., Jørgensen, B. B., & D'Hondt, S. (2012). Aerobic microbial respiration in 86-million-year-old deep-sea red clay. Science, 336(6083), 922–925. http://doi.org/10.1126/science.1219424"
        = f.input :paper, label: "Reference to the paper where it was found" ,placeholder: "LaRowe, D. E., & Amend, J. P. (2015). Catabolic rates, population sizes and doubling/replacement times of microorganisms in natural settings. American Journal of Science, 315(3), 167–203. http://doi.org/10.2475/03.2015.01", hint: "fill this if you found the data not in the original paper but in different with reference to the original"
    .row
      .col-md-4
        .form-actions
          = f.button :submit, class: "btn btn-primary"
          

app/views/gibbs_rates_observations/edit.html.haml
.row
  .col-md-6
    %h4 Edit the observation
  .col-md-6
    = link_to 'Delete GibbsRatesObservation', @gibbs_rates_observation, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-danger pull-right"

= render 'form'
%p

app/views/gibbs_rates_observations/index.csv.erb
<%- headers = ['reaction_name', 'donor', 'acceptor', 'reaction', 'lab', 'environment_type', 'location_name', 'rate', 'gibbs_energy', 'reference', 'paper', 'user_id', 'lat', 'lng', 'add_info', 'gibbs_units', 'rate_units'] -%>
<%= CSV.generate_line headers %>
<%- @gibbs_rates_observations.each do |gibbs_rates_observation| -%>
  <%= CSV.generate_line([ gibbs_rates_observation.reaction_name, gibbs_rates_observation.donor, gibbs_rates_observation.acceptor, gibbs_rates_observation.reaction, gibbs_rates_observation.lab, gibbs_rates_observation.environment_type, gibbs_rates_observation.location_name, gibbs_rates_observation.rate, gibbs_rates_observation.gibbs_energy, gibbs_rates_observation.reference, gibbs_rates_observation.paper, gibbs_rates_observation.user_id, gibbs_rates_observation.lat, gibbs_rates_observation.lng, gibbs_rates_observation.add_info, gibbs_rates_observation.gibbs_units, gibbs_rates_observation.rate_units ]).html_safe %>
<%- end -%>

app/views/gibbs_rates_observations/index.html.haml
%h1 Observations

%table{class: 'table'}
  %thead
    %tr
      %th ID
      %th Reaction name
      %th Lab?
      %th Type
      %th Where
      %th Rate
      %th Gibbs energy
      %th Reference
      %th

  %tbody
    - @gibbs_rates_observations.each do |gibbs_rates_observation|
      %tr
        %td= link_to gibbs_rates_observation.id, gibbs_rates_observation
        %td= gibbs_rates_observation.reaction_name
        - if gibbs_rates_observation.lab 
          %td Lab
        - else
          %td In Situ
        %td= gibbs_rates_observation.environment_type
        %td= gibbs_rates_observation.location_name
        %td= gibbs_rates_observation.rate.to_s + ', ' + gibbs_rates_observation.rate_units
        %td= gibbs_rates_observation.gibbs_energy.to_s + ', ' + gibbs_rates_observation.gibbs_units
        %td= first_author(gibbs_rates_observation.reference)

%br

.row
  .col-md-6
    .pull-left
      = link_to 'New Observation', new_gibbs_rates_observation_path
  .col-md-6
    .pull-right
      = link_to 'Export as CSV', gibbs_rates_observations_path(format: :csv)

app/views/gibbs_rates_observations/new.html.haml
%h1 New gibbs_rates_observation

= render 'form'

app/views/gibbs_rates_observations/show.html.haml
%p#notice= notice

.row
  .col-sm-6
    %p
    .row
      .col-md-4
        %b Reaction name:
      .col-md-8
        = @gibbs_rates_observation.reaction_name
    %p
    .row
      .col-md-4
        %b Donor:
      .col-md-8
        = @gibbs_rates_observation.donor
    %p
    .row
      .col-md-4
        %b Acceptor:
      .col-md-8
        = @gibbs_rates_observation.acceptor
    %p
    .row
      .col-md-4
        %b Reaction:
      .col-md-8
        = @gibbs_rates_observation.reaction
    %p
    .row
      .col-md-4
        %b Measured: 
      .col-md-8
        - if @gibbs_rates_observation.lab
          In the lab
        - else
          in Situ
    %p
    .row
      .col-md-4
        %b Rate:
      .col-md-8
        = @gibbs_rates_observation.rate
        = @gibbs_rates_observation.rate_units
    %p
    .row
      .col-md-4
        %b Gibbs energy:
      .col-md-8
        = @gibbs_rates_observation.gibbs_energy
        = @gibbs_rates_observation.gibbs_units
    %p
    .row
      .col-md-4
        %b Reference:
      .col-md-8
        = @gibbs_rates_observation.reference
    %p
    .row
      .col-md-4
        %b Paper:
      .col-md-8
        = @gibbs_rates_observation.paper
    %p
    .row
      .col-md-4
        %b Additional info:
      .col-md-8
        =@gibbs_rates_observation.add_info
  .col-sm-6
    %p
    .row
      .col-md-4
        %b location_name:
      .col-md-8
        = @gibbs_rates_observation.location_name
    #map{style: 'width: 400px; height: 400px;'}
    %p
    .row
      .col-md-4
        %b Latitude:
      .col-md-8
        = @gibbs_rates_observation.lat 
    .row
      .col-md-4
        %b Longitude:
      .col-md-8
        = @gibbs_rates_observation.lng 
    .row
      .col-md-4
        %b Type:
      .col-md-8
        = @gibbs_rates_observation.environment_type
    .row
      .col-md-4
        %b Added by:
      .col-md-8
        = @gibbs_rates_observation.owner.name
        = time_ago_in_words(@gibbs_rates_observation.created_at)
        ago

.pull-left
  = link_to 'Back', gibbs_rates_observations_path
.pull-right
  = link_to 'Edit', edit_gibbs_rates_observation_path(@gibbs_rates_observation), class: "btn btn-primary"
  = link_to 'Delete', @gibbs_rates_observation, method: :delete, data:  { confirm: 'Are you sure?' }, class: 'btn btn-danger'


:javascript
  $(document).ready(function(){
    var gibbs_rates_observation = #{@gibbs_rates_observation.to_json}    // pass ruby variable to javascript
    gmap_show(gibbs_rates_observation);    // init show map for gibbs_rates_observation card (only print marker)
  });